title: Klaslab
description: "Mijn reis als natuurkundedocent die met AI in en om de klas wil werken."
url: https://klaslab.nl
author: KlasLab
locale: nl_NL

theme: minima
plugins:
  - jekyll-feed

# Optioneel, maar handig:
show_excerpts: true
header_pages:
  - about.md
